version: "3"
services:
  mongo:
    image: mongo:3.4.18
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - .db:/data/db
    command: mongod --smallfiles
  backend:
    image: kovacszsolt/blog-backend-nodejs:latest
    restart: on-failure
    depends_on:
      - mongo
    environment:
      PORT: "8090"
      MONGO_SERVER: "mongo:27017"
      MONGO_DATABASE: "database"
      TMP_UPLOAD_PATH: "./tmp"
      UPLOAD_FILES: "./images"
      ALLOW_ORIGIN: "*"
      ROOT: "/admin/"
      NO_HEADER_URL: "[\"/\",\"session/add/\"]"
      NO_USER_URL: "[]"
      SWAGGER_ALLOW_ORIGIN: "*"
      SWAGGER_SCHEMES: "[\"https\",\"http\"]"
      SWAGGER_PORT: "8000"
      SWAGGER_HOST: "localhost:8090"
      SWAGGER_BASEPATH: "/admin/"
      SWAGGER_URL: "/"
      SWAGGER_FILES: "[]"
  nginx:
    image: nginx:latest
    volumes:
      - ./:/home/node/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx
    ports:
      - 8000:80
    depends_on:
      - mongo
      - backend
